/* tslint:disable */
/**
 * DO NOT MODIFY!
 *
 * This file is generated by routekit.
 */

export const ROUTES = {
  f: 11,
  p: "/",
  c: [{
    f: 43,
    p: "static",
    c: {
      f: 11,
      p: "/",
      c: [{
        f: 3,
        p: "a",
        d: { "location": "static3" }
      }, {
        f: 3,
        p: "b",
        d: { "location": "static4" }
      }],
      d: { "location": "static2" }
    },
    d: { "location": "static1" }
  }, {
    f: 50,
    p: "param/",
    c: {
      f: 45,
      c: {
        f: 11,
        p: "/",
        c: [{
          f: 3,
          p: "b",
          d: { "location": "param3" }
        }, {
          f: 3,
          p: "c",
          d: { "location": "param4" }
        }],
        d: { "location": "param2" }
      },
      d: { "location": "param1" }
    }
  }, {
    f: 67,
    p: "catchAll/",
    d: { "location": "catchAll1" }
  }, {
    f: 50,
    p: "nested/",
    c: {
      f: 44,
      c: {
        f: 51,
        p: "/",
        c: {
          f: 45,
          c: {
            f: 50,
            p: "/",
            c: {
              f: 5,
              d: { "location": "nested3" }
            }
          },
          d: { "location": "nested2" }
        },
        d: { "location": "nested1" }
      }
    }
  }, {
    f: 26,
    p: "mix/",
    c: [{
      f: 45,
      c: {
        f: 3,
        p: "/static",
        d: { "location": "mix2" }
      },
      d: { "location": "mix1" }
    }, {
      f: 43,
      p: "static",
      c: {
        f: 50,
        p: "/",
        c: {
          f: 5,
          d: { "location": "mix4" }
        }
      },
      d: { "location": "mix3" }
    }]
  }],
  d: { "location": "home" }
};

export interface Stringifiable {
  toString(): string;
}

export function static1() {
  return "/static";
}

export function static2() {
  return "/static/";
}

export function static3() {
  return "/static/a";
}

export function static4() {
  return "/static/b";
}

export function param1(a: Stringifiable) {
  return "/param/" + a;
}

export function param2(a: Stringifiable) {
  return "/param/" + a + "/";
}

export function param3(a: Stringifiable) {
  return "/param/" + a + "/b";
}

export function param4(a: Stringifiable) {
  return "/param/" + a + "/c";
}

export function catchAll1(w: Stringifiable) {
  if (w === undefined) {
    return "/catchAll/"
  }
  return "/catchAll/" + w;
}

export function nested1(a: Stringifiable) {
  return "/nested/" + a + "/";
}

export function nested2(a: Stringifiable, b: Stringifiable) {
  return "/nested/" + a + "/" + b;
}

export function nested3(a: Stringifiable, b: Stringifiable, c: Stringifiable) {
  return "/nested/" + a + "/" + b + "/" + c;
}

export function mix1(a: Stringifiable) {
  return "/mix/" + a;
}

export function mix2(a: Stringifiable) {
  return "/mix/" + a + "/static";
}

export function mix3() {
  return "/mix/static";
}

export function mix4(b: Stringifiable) {
  return "/mix/static/" + b;
}

export function home() {
  return "/";
}

export const REVERSE = {
  "static1": static1,
  "static2": static2,
  "static3": static3,
  "static4": static4,
  "param1": param1,
  "param2": param2,
  "param3": param3,
  "param4": param4,
  "catchAll1": catchAll1,
  "nested1": nested1,
  "nested2": nested2,
  "nested3": nested3,
  "mix1": mix1,
  "mix2": mix2,
  "mix3": mix3,
  "mix4": mix4,
  "home": home
};
