import * as fs from 'node:fs/promises';
import { dirname } from 'node:path';

/** Create a route definition with a path and associated state. */
export function r(path: string, state: string | number): Route {
  if (typeof state === 'number') {
    state = String(state);
  }
  return { path, state };
}

/** Options for `emitRoutes`. */
export interface EmitRoutesOptions {
  /** Route definitions to build. */
  routes: Route[];
  /** Output file path. */
  path?: string;
  /** Return type annotation for the generated `routeMatch` function. */
  type?: string;
  /** Custom code inserted after imports. */
  prelude?: string;
}

/**
 * Build routes into a trie, serialize to a flat array, and write
 * a generated module that exports a `routeMatch` function.
 */
export async function emitRoutes(options: EmitRoutesOptions): Promise<FlatTree> {
  const routes = toFlat(build(options.routes));
  const signature = options.type ? `(path: string): ${options.type}` : `(path)`;
  const prelude = options.prelude ? '\n' + options.prelude : '';
  const code = `/* File is autogenerated by "routekit" */
import { resolve } from "routekit";${prelude}

const ROUTES = ${emitFlatTree(routes)};

export const routeMatch = ${signature} => resolve(ROUTES, path);
`;

  if (options.path) {
    await updateFile(options.path, code);
  }
  return routes;
}

/** Serialize a FlatTree into a JavaScript object literal string. */
function emitFlatTree(tree: FlatTree): string {
  let out = '{\n';
  out += '  f: [' + tree.f.join(', ') + '],\n';
  out += '  p: [' + tree.p.map((p) => JSON.stringify(p)).join(', ') + '],\n';
  out += '  s: [' + tree.s.join(', ') + '],\n';
  out += '}';

  return out;
}

/** Node type flags used during tree serialization. Mirrors RouteNodeFlags. */
const enum FlatNodeFlags {
  Endpoint = 1,
  Static = 1 << 1,
  NotSlash = 1 << 2,
  CatchAll = 1 << 3,
}

/** Serialized trie stored as parallel arrays. */
export interface FlatTree {
  f: number[];
  p: string[];
  s: string[];
}

/**
 * Flatten a trie node into the parallel arrays in pre-order.
 *
 * Flags encode: Endpoint | Static | NotSlash | CatchAll | (childrenCount << 5).
 * Static children are emitted before the variable child so that
 * static routes take precedence during resolution.
 * Catch-all children are emitted last.
 */
function _pushFlatNode(tree: FlatTree, node: RouteNode): void {
  let flags = 0;

  // Root "/" is Static but not NotSlash — no path entry needed
  if (node.path !== '') {
    flags |= FlatNodeFlags.Static;
    if (node.path !== '/') {
      flags |= FlatNodeFlags.NotSlash;
      tree.p.push(node.path);
    }
  }

  if (node.state !== null) {
    flags |= FlatNodeFlags.Endpoint;
    tree.s.push(node.state);
  }

  if (node.isCatchAll) {
    flags |= FlatNodeFlags.CatchAll;
  }

  const staticChildren = getStaticChildren(node);
  const paramChild = getVariableChild(node);
  const catchAllChild = getCatchAllChild(node);

  let childrenLength = staticChildren.length;
  if (paramChild) {
    childrenLength += 1;
  }
  if (catchAllChild) {
    childrenLength += 1;
  }

  tree.f.push(flags | (childrenLength << 5));

  // Emit static children first, then variable child, then catch-all child
  if (staticChildren.length > 0) {
    for (const c of staticChildren) {
      _pushFlatNode(tree, c);
    }
  }
  if (paramChild) {
    _pushFlatNode(tree, paramChild);
  }
  if (catchAllChild) {
    _pushFlatNode(tree, catchAllChild);
  }
}

/** Convert a trie root into a FlatTree. */
function toFlat(node: RouteNode): FlatTree {
  const tree = { f: [], p: [], s: [] };
  _pushFlatNode(tree, node);
  return tree;
}

/** A trie node. Variable nodes have path=""; static nodes have a non-empty path. */
interface RouteNode {
  path: string;
  children: RouteNode[];
  state: string | null;
  isCatchAll: boolean;
}

/** A user-provided route definition. */
export interface Route {
  readonly path: string;
  readonly state: string;
}

/**
 * Build a trie from an array of route definitions.
 *
 * Routes are parsed character-by-character:
 * - ":" starts a variable segment (consumes until "/" or end)
 * - "*" starts a catch-all segment (consumes until "/" or end, must be last)
 * - Everything else is a static segment
 *
 * Static segments are inserted via pushStatic, which handles
 * prefix splitting when a new route shares a prefix with an existing node.
 */
function build(routes: Route[]): RouteNode {
  const root = createNode('/');

  for (const { path, state } of routes) {
    if (path === '') {
      throw new Error('Invalid path, path is empty');
    }

    if (path.charCodeAt(0) !== 47) {
      throw new Error("Invalid path, path should start with a '/' character");
    }

    let n = root;
    let start = 0;
    let i = 0;

    while (i < path.length) {
      if (path.charCodeAt(i) === 58) {
        // ":" === 58
        n = pushStatic(n, path.slice(start, i));

        start = i;
        while (i < path.length && path.charCodeAt(i) !== 47) {
          // skip until "/" character
          i++;
        }
        if (i - start <= 1) {
          throw new Error('Invalid variable, variable should have a name');
        }
        n = pushVariable(n);
        start = i;
      } else if (path.charCodeAt(i) === 42) {
        // "*" === 42
        n = pushStatic(n, path.slice(start, i));

        start = i;
        while (i < path.length && path.charCodeAt(i) !== 47) {
          // skip until "/" character
          i++;
        }
        if (i - start <= 1) {
          throw new Error('Invalid catch-all, catch-all should have a name');
        }
        // Catch-all must be the last segment
        if (i < path.length) {
          throw new Error('Invalid catch-all, catch-all must be the last segment');
        }
        n = pushCatchAll(n);
        start = i;
      } else {
        i++;
      }
    }
    if (i > start) {
      n = pushStatic(n, path.slice(start, i));
    }

    n.state = state;
  }

  return root;
}

/** Create a new trie node. Variable nodes use path=""; static nodes get an explicit path. */
function createNode(path = ''): RouteNode {
  return { path, children: [], state: null, isCatchAll: false };
}

/**
 * Insert a static path segment into the trie, splitting existing nodes
 * when necessary.
 *
 * Returns the leaf node for the inserted path.
 *
 * Cases:
 * 1. Node has empty path — find or create a child matching the first char
 * 2. LCP < existing path — split the existing node at the divergence point
 * 3. LCP < new path — descend into the matching child
 * 4. LCP fully covers both — return the existing node
 */
function pushStatic(cn: RouteNode, path: string): RouteNode {
  if (cn.path === '') {
    const c = findStaticChildByLabel(cn, path[0]);
    if (c === void 0) {
      const n = createNode(path);
      cn.children.push(n);
      return n;
    }

    cn = c;
  }

  let s = path;

  while (true) {
    const nl = cn.path.length;
    const sl = s.length;
    const max = Math.max(nl, sl);
    let i = 0;

    while (i < max && cn.path.charCodeAt(i) === s.charCodeAt(i)) {
      i++;
    }

    if (i < nl) {
      // split
      const c = createNode(cn.path.slice(i));
      c.children = cn.children;
      c.state = cn.state;

      cn.path = cn.path.slice(0, i);
      cn.children = [c];
      cn.state = null;

      if (sl === i) {
        return cn;
      }

      const n = createNode(s.slice(i));
      cn.children.push(n);
      return n;
    } else if (i < sl) {
      // next node
      s = s.slice(i);
      const c = findStaticChildByLabel(cn, s[0]);
      if (c === void 0) {
        const n = createNode(s);
        cn.children.push(n);
        return n;
      }
      cn = c;
    } else {
      return cn;
    }
  }
}

/** Get or create a variable child (path="") for the given node. */
function pushVariable(cn: RouteNode): RouteNode {
  let n = getVariableChild(cn);
  if (n === void 0) {
    n = createNode();
    cn.children.push(n);
  }
  return n;
}

/** Get or create a catch-all child for the given node. */
function pushCatchAll(cn: RouteNode): RouteNode {
  let n = getCatchAllChild(cn);
  if (n === void 0) {
    n = createNode();
    n.isCatchAll = true;
    cn.children.push(n);
  }
  return n;
}

/** Find the catch-all child if one exists. */
function getCatchAllChild(cn: RouteNode): RouteNode | undefined {
  return cn.children.find((n) => n.isCatchAll);
}

/** Find a static child whose path starts with the given character. */
function findStaticChildByLabel(cn: RouteNode, label: string): RouteNode | undefined {
  return cn.children.find((n) => n.path.length > 0 && n.path[0] === label);
}

/** Find the variable child (path === "") if one exists. Excludes catch-all nodes. */
function getVariableChild(cn: RouteNode): RouteNode | undefined {
  return cn.children.find((n) => n.path === '' && !n.isCatchAll);
}

/** Get all static children (path !== ""). */
function getStaticChildren(cn: RouteNode): RouteNode[] {
  return cn.children.filter((n) => n.path !== '');
}

/**
 * Write only when contents has changed. This avoids unnecessary rebuilds triggered by timestamp
 * changes.
 */
async function updateFile(path: string, content: string | Uint8Array): Promise<void> {
  await fs.mkdir(dirname(path), { recursive: true });
  try {
    const c = await fs.readFile(path);
    if (typeof content === 'string') {
      content = new TextEncoder().encode(content);
    }
    if (c.equals(content)) {
      return;
    }
  } catch {}

  await fs.writeFile(path, content);
}
